port: 8080
algorithm: round-robin # round-robin
health_check_interval: 10s
servers:
  - http://localhost:5000
  - http://localhost:5001
  - http://localhost:5002
  - http://localhost:5003
  - http://localhost:5004